const SUPABASE_URL_KEY="tv_supabase_url", SUPABASE_ANON_KEY="tv_supabase_anon";
let sb=null, currentUser=null, profile=null, accounts=[], trades=[], authMode="login", resetMode=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg,type="info"){const r=$("#toastRoot"),x=document.createElement("div");x.className="toast "+type;x.textContent=msg;r.appendChild(x);setTimeout(()=>x.remove(),3200)}
const cfg=window.TRADEVAULT_CONFIG||{};
const savedUrl=cfg.supabaseUrl||localStorage.getItem(SUPABASE_URL_KEY),
      savedKey=cfg.supabaseAnonKey||localStorage.getItem(SUPABASE_ANON_KEY);
if(cfg.supabaseUrl&&cfg.supabaseAnonKey){localStorage.setItem(SUPABASE_URL_KEY,cfg.supabaseUrl);localStorage.setItem(SUPABASE_ANON_KEY,cfg.supabaseAnonKey);}
if(savedUrl&&savedKey) initSupabase(savedUrl,savedKey);
function initSupabase(url,key){try{sb=window.supabase.createClient(url,key);sb.auth.onAuthStateChange((event,session)=>{setTimeout(()=>handleSession(session),0)});sb.auth.getSession().then(({data})=>handleSession(data.session));}catch(e){toast("Supabase configuration could not be loaded","error")}}
function openAuth(mode="login"){authMode=mode;resetMode=false;$("#authModal").classList.remove("hidden");renderAuth()}
function renderAuth(){
 const p=$("#authPanel");
 if(resetMode){p.innerHTML=`<h2>Reset password</h2><p class="auth-sub">Choose a new password for your TradeVault account.</p><form class="auth-form" id="resetForm"><label>New password<input id="newPassword" type="password" minlength="8" required></label><label>Confirm password<input id="newPassword2" type="password" minlength="8" required></label><button class="btn primary full">Update password</button></form><div class="auth-links"><button id="backAuth">Back to login</button></div>`;$("#resetForm").onsubmit=resetPassword;$("#backAuth").onclick=()=>{resetMode=false;authMode="login";renderAuth()};return}
 if(authMode==="signup"){p.innerHTML=`<h2>Create your account</h2><p class="auth-sub">Your trading workspace starts here.</p><form class="auth-form" id="signupForm">
 <label>First name<input id="firstName" required autocomplete="given-name"></label>
 <label>Middle name <span class="muted">(optional)</span><input id="middleName" autocomplete="additional-name"></label>
 <label>Surname<input id="surname" required autocomplete="family-name"></label>
 <label>Email<input id="email" type="email" required autocomplete="email"></label>
 <label>Phone number<input id="phone" type="tel" required autocomplete="tel" placeholder="+234..."></label>
 <label>Password<input id="password" type="password" minlength="8" required autocomplete="new-password"><div class="password-strength"><i id="pwBar"></i></div></label>
 <label>Confirm password<input id="password2" type="password" minlength="8" required autocomplete="new-password"></label>
 <label class="checkline"><input id="terms" type="checkbox" required> I agree to the Terms, Privacy Policy and Risk Disclosure.</label>
 <button class="btn primary full">Create free account</button></form>
 <div class="divider">OR</div><button class="btn secondary full" id="googleBtn">Continue with Google</button>
 <div class="auth-links"><button id="toLogin">Already have an account? Log in</button></div>`;
 $("#signupForm").onsubmit=signup;$("#password").oninput=e=>{let n=e.target.value.length;$("#pwBar").style.width=Math.min(100,n*12.5)+"%"};$("#toLogin").onclick=()=>{authMode="login";renderAuth()};$("#googleBtn").onclick=googleLogin;return}
 p.innerHTML=`<h2>Welcome back</h2><p class="auth-sub">Log in to your private trading workspace.</p><form class="auth-form" id="loginForm"><label>Email<input id="email" type="email" required autocomplete="email"></label><label>Password<input id="password" type="password" required autocomplete="current-password"></label><button class="btn primary full">Log in</button></form><div class="auth-links"><button id="forgotBtn">Forgot password?</button><button id="toSignup">Create account</button></div><div class="divider">OR</div><button class="btn secondary full" id="googleBtn">Continue with Google</button><p class="auth-sub" style="margin-top:18px">New here? Start free — no payment required.</p>`;
 $("#loginForm").onsubmit=login;$("#forgotBtn").onclick=forgotPassword;$("#toSignup").onclick=()=>{authMode="signup";renderAuth()};$("#googleBtn").onclick=googleLogin;
}
async function signup(e){e.preventDefault();if(!sb){toast("Connect Supabase first. See README.","error");return}const first=$("#firstName").value.trim(),middle=$("#middleName").value.trim();const sn=$("#surname").value.trim(),em=$("#email").value.trim(),ph=$("#phone").value.trim(),pw=$("#password").value;if(pw!==$("#password2").value){toast("Passwords do not match","error");return}const {data,error}=await sb.auth.signUp({email:em,password:pw,options:{data:{first_name:first,middle_name:middle,surname:sn,phone:ph}}});if(error){toast(error.message,"error");return}toast(data.session?"Account created":"Check your email to verify your account","success");if(data.session) closeModal("authModal")}
async function login(e){e.preventDefault();if(!sb){toast("Connect Supabase first. See README.","error");return}const {error}=await sb.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});if(error)toast(error.message,"error");else closeModal("authModal")}
async function googleLogin(){if(!sb){toast("Connect Supabase first. See README.","error");return}const {error}=await sb.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.href}});if(error)toast(error.message,"error")}
async function forgotPassword(){const em=prompt("Enter your TradeVault email");if(!em)return;if(!sb){toast("Connect Supabase first.","error");return}const {error}=await sb.auth.resetPasswordForEmail(em,{redirectTo:location.href});if(error)toast(error.message,"error");else toast("Password reset email sent","success")}
async function resetPassword(e){e.preventDefault();const a=$("#newPassword").value,b=$("#newPassword2").value;if(a!==b)return toast("Passwords do not match","error");const {error}=await sb.auth.updateUser({password:a});if(error)toast(error.message,"error");else{toast("Password updated","success");resetMode=false;authMode="login";renderAuth()}}
function closeModal(id){$("#"+id).classList.add("hidden")}
async function handleSession(session){currentUser=session?.user||null;if(currentUser){await loadUser();showApp()}else showPublic()}
async function loadUser(){if(!sb||!currentUser)return;let r=await sb.from("profiles").select("*").eq("id",currentUser.id).maybeSingle();profile=r.data||{};let a=await sb.from("trading_accounts").select("*").eq("user_id",currentUser.id).order("created_at");accounts=a.data||[];let t=await sb.from("trades").select("*").eq("user_id",currentUser.id).order("trade_date",{ascending:false});trades=t.data||[];$("#workspaceName").textContent=profile.workspace_name||"My Trading";$("#profileAvatar").textContent=(profile.first_name||currentUser.email||"U").slice(0,1).toUpperCase()}
function showPublic(){$("#publicApp").classList.remove("hidden");$("#appShell").classList.add("hidden");$("#userBtn").classList.add("hidden");$("#loginBtn").classList.remove("hidden");$("#signupBtn").classList.remove("hidden")}
function showApp(){$("#publicApp").classList.add("hidden");$("#appShell").classList.remove("hidden");$("#loginBtn").classList.add("hidden");$("#signupBtn").classList.add("hidden");$("#userBtn").classList.remove("hidden");renderApp("dashboard")}
function renderApp(view){$$(".side-item[data-appview]").forEach(x=>x.classList.toggle("active",x.dataset.appview===view));const title={dashboard:"Overview",trades:"Trades",analytics:"Analytics",risk:"Risk monitor",psychology:"Psychology",playbook:"Playbook",journal:"Journal",settings:"Settings"}[view]||"Overview";$("#appTitle").textContent=title;$("#appGreeting").textContent=`Welcome, ${profile?.first_name||"trader"}`;const c=$("#appContent");if(view==="dashboard")c.innerHTML=dashboardHTML();if(view==="trades")c.innerHTML=tradesHTML();if(view==="analytics")c.innerHTML=analyticsHTML();if(view==="risk")c.innerHTML=riskHTML();if(view==="psychology")c.innerHTML=psychologyHTML();if(view==="playbook")c.innerHTML=playbookHTML();if(view==="journal")c.innerHTML=journalHTML();if(view==="settings")c.innerHTML=settingsHTML();bindAppView(view)}
function dashboardHTML(){const pnl=trades.reduce((s,t)=>s+Number(t.pnl||0),0),wins=trades.filter(t=>Number(t.pnl)>0).length,wr=trades.length?wins/trades.length*100:0,avg=trades.length?trades.reduce((s,t)=>s+Number(t.r_multiple||0),0)/trades.length:0;return `<div class="app-content-grid"><div class="stat-card"><small>Net P&L</small><strong class="${pnl>=0?'win':'loss'}">${fmtMoney(pnl)}</strong><em>${trades.length} closed trades</em></div><div class="stat-card"><small>Win rate</small><strong>${wr.toFixed(1)}%</strong><em>${wins} wins / ${trades.length-wins} losses</em></div><div class="stat-card"><small>Average R</small><strong>${avg.toFixed(2)}R</strong><em>Per recorded trade</em></div><div class="stat-card"><small>Journal status</small><strong>${trades.length?"Active":"Ready"}</strong><em>Keep documenting</em></div></div><div class="two-col"><div class="panel"><div class="panel-title"><h3>Equity curve</h3><button class="btn primary" id="newTradeBtn">+ New trade</button></div><div style="height:260px"><svg id="equitySvg" viewBox="0 0 800 260" width="100%" height="100%" preserveAspectRatio="none"></svg></div></div><div class="panel"><div class="panel-title"><h3>Recent trades</h3></div>${recentRows(5)}</div></div><div class="panel" style="margin-top:16px"><div class="panel-title"><h3>Quick checklist</h3><span class="tag">Pre-trade</span></div><div class="check-list"><div class="check">☑ Higher-timeframe bias defined</div><div class="check">☑ Liquidity objective identified</div><div class="check">☐ Entry model confirmed</div><div class="check">☐ Risk is within account rules</div></div></div>`}
function recentRows(n){if(!trades.length)return `<div class="empty">No trades yet. Log your first trade.</div>`;return `<div class="table-wrap"><table class="trade-table"><thead><tr><th>Date</th><th>Symbol</th><th>Dir</th><th>P&L</th></tr></thead><tbody>${trades.slice(0,n).map(t=>`<tr><td>${new Date(t.trade_date||t.created_at).toLocaleDateString()}</td><td>${esc(t.symbol)}</td><td>${esc(t.direction)}</td><td class="${Number(t.pnl)>=0?'win':'loss'}">${fmtMoney(t.pnl)}</td></tr>`).join("")}</tbody></table></div>`}
function tradesHTML(){return `<div class="panel"><div class="panel-title"><h3>Trade journal</h3><button class="btn primary" id="newTradeBtn">+ New trade</button></div><div class="toolbar"><input class="input" id="tradeSearch" placeholder="Search symbol, setup or notes..."></div><div id="tradeTable">${recentRows(100)}</div></div>`}
function analyticsHTML(){const groups={};trades.forEach(t=>{const k=t.setup||"Other";groups[k]=(groups[k]||0)+Number(t.pnl||0)});const max=Math.max(1,...Object.values(groups).map(v=>Math.abs(v)));return `<div class="panel"><div class="panel-title"><h3>Performance by setup</h3></div>${Object.keys(groups).length?Object.entries(groups).map(([k,v])=>`<div class="bar-row"><div class="bar-label"><span>${esc(k)}</span><b class="${v>=0?'win':'loss'}">${fmtMoney(v)}</b></div><div class="bar"><i style="width:${Math.max(4,Math.abs(v)/max*100)}%"></i></div></div>`).join(""):`<div class="empty">Log trades to unlock analytics.</div>`}</div><div class="two-col"><div class="panel"><h3>Direction</h3>${directionStats()}</div><div class="panel"><h3>Sessions</h3>${sessionStats()}</div></div>`}
function directionStats(){return ["Long","Short"].map(d=>{const a=trades.filter(t=>t.direction===d),p=a.reduce((s,t)=>s+Number(t.pnl||0),0);return `<div class="bar-row"><div class="bar-label"><span>${d}</span><b>${a.length} trades · ${fmtMoney(p)}</b></div><div class="bar"><i style="width:${trades.length?Math.max(3,a.length/trades.length*100):3}%"></i></div></div>`}).join("")}
function sessionStats(){return ["Asia","London","New York","Other"].map(d=>{const a=trades.filter(t=>t.session===d),p=a.reduce((s,t)=>s+Number(t.pnl||0),0);return `<div class="bar-row"><div class="bar-label"><span>${d}</span><b>${a.length} · ${fmtMoney(p)}</b></div><div class="bar"><i style="width:${trades.length?Math.max(3,a.length/trades.length*100):3}%"></i></div></div>`}).join("")}
function riskHTML(){const a=accounts[0],bal=Number(a?.starting_balance||10000)+trades.reduce((s,t)=>s+Number(t.pnl||0),0),start=Number(a?.starting_balance||10000),dd=start?Math.max(0,(start-bal)/start*100):0;return `<div class="panel"><div class="panel-title"><h3>Risk monitor</h3><span class="tag">${a?esc(a.name):"Default account"}</span></div><div class="risk-box"><div class="risk-metric"><small>Balance</small><b>${fmtMoney(bal)}</b><span>Starting ${fmtMoney(start)}</span></div><div class="risk-metric"><small>Drawdown</small><b>${dd.toFixed(2)}%</b><span>Based on current journal</span></div><div class="risk-metric"><small>Trades logged</small><b>${trades.length}</b><span>Keep risk consistent</span></div></div></div><div class="panel" style="margin-top:16px"><h3>Guardrails</h3><div class="check-list"><div class="check">✓ Use a predefined risk percentage</div><div class="check">✓ Stop after your daily loss limit</div><div class="check">✓ Avoid revenge trades</div><div class="check">✓ Review before increasing size</div></div></div>`}
function psychologyHTML(){const g={};trades.forEach(t=>g[t.emotion||"Unspecified"]=(g[t.emotion||"Unspecified"]||0)+1);return `<div class="panel"><div class="panel-title"><h3>Execution psychology</h3></div>${Object.keys(g).length?Object.entries(g).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><div class="bar-label"><span>${esc(k)}</span><b>${v} trade${v===1?"":"s"}</b></div><div class="bar"><i style="width:${v/trades.length*100}%"></i></div></div>`).join(""):`<div class="empty">Record emotions on trades to see patterns.</div>`}</div>`}
function playbookHTML(){return `<div class="two-col"><div class="panel"><div class="panel-title"><h3>My playbook</h3><button class="btn primary" onclick="toast('Playbook editor is ready for the next database module.')">+ Add rule</button></div><div class="check-list"><div class="check"><b>FVG continuation</b><br><small>Define bias → liquidity → displacement → retracement → entry.</small></div><div class="check"><b>Liquidity sweep</b><br><small>Record the pool taken, displacement and confirmation.</small></div><div class="check"><b>Opening range</b><br><small>Document session range and invalidation before entry.</small></div></div></div><div class="panel"><h3>Rule quality</h3><p class="muted">The playbook becomes more useful when every rule can be tested against your journal.</p></div></div>`}
function journalHTML(){return `<div class="panel"><div class="panel-title"><h3>Daily journal</h3><button class="btn primary" onclick="toast('Daily journal editor will save to your cloud workspace.')">+ New entry</button></div><div class="empty">No journal entries yet. Use this space for pre-market plans, end-of-day reviews and lessons.</div></div>`}
function settingsHTML(){return `<div class="two-col"><div class="panel"><h3>Profile</h3><div class="form-grid"><label>First name<input id="setFirst" value="${esc(profile?.first_name||"")}"></label><label>Surname<input id="setSurname" value="${esc(profile?.surname||"")}"></label><label>Phone<input id="setPhone" value="${esc(profile?.phone||"")}"></label><label>Workspace<input id="setWorkspace" value="${esc(profile?.workspace_name||"My Trading")}"></label></div><button class="btn primary" style="margin-top:16px" id="saveProfile">Save profile</button></div><div class="panel"><h3>Account</h3><p class="muted">${esc(currentUser?.email||"")}</p><button class="btn secondary" id="resetFromSettings">Change password</button><hr><h3>Data</h3><button class="btn secondary" onclick="exportData()">Export journal JSON</button></div></div>`}
function bindAppView(view){const nt=$("#newTradeBtn");if(nt)nt.onclick=()=>openTrade();const search=$("#tradeSearch");if(search)search.oninput=()=>{const q=search.value.toLowerCase();const old=trades;trades=old.filter(t=>JSON.stringify(t).toLowerCase().includes(q));$("#tradeTable").innerHTML=recentRows(100);trades=old};const save=$("#saveProfile");if(save)save.onclick=saveProfile;const reset=$("#resetFromSettings");if(reset)reset.onclick=forgotPassword;if(view==="dashboard")setTimeout(drawEquity,30)}
function drawEquity(){const svg=$("#equitySvg");if(!svg)return;let eq=Number(accounts[0]?.starting_balance||10000),pts=[`0,220`];trades.slice().reverse().forEach((t,i)=>{eq+=Number(t.pnl||0);pts.push(`${(i+1)*760/Math.max(1,trades.length-1)},${220-Math.max(-1,Math.min(1,(eq-(accounts[0]?.starting_balance||10000))/1000))*150}`)});svg.innerHTML=`<polyline points="${pts.join(" ")}" fill="none" stroke="#686af1" stroke-width="4"/><line x1="0" y1="220" x2="800" y2="220" stroke="#e5e8ef"/>`}
async function openTrade(){if(!accounts.length&&sb){await createDefaultAccount()}$("#tradeAccount").innerHTML=(accounts.length?accounts:[{id:"",name:"Default"}]).map(a=>`<option value="${a.id}">${esc(a.name||"Trading account")}</option>`).join("");$("#tradeModal").classList.remove("hidden")}
async function createDefaultAccount(){const {data,error}=await sb.from("trading_accounts").insert({user_id:currentUser.id,name:"Main Account",account_type:"personal",starting_balance:10000,currency:"USD"}).select().single();if(!error&&data)accounts=[data]}
async function saveTrade(e){e.preventDefault();if(!sb)return;const row={user_id:currentUser.id,account_id:$("#tradeAccount").value||accounts[0]?.id||null,symbol:$("#tradeSymbol").value.trim().toUpperCase(),direction:$("#tradeDirection").value,pnl:Number($("#tradePnl").value),r_multiple:Number($("#tradeR").value||0),setup:$("#tradeSetup").value,session:$("#tradeSession").value,emotion:$("#tradeEmotion").value,notes:$("#tradeNotes").value,trade_date:new Date().toISOString()};const {data,error}=await sb.from("trades").insert(row).select().single();if(error)toast(error.message,"error");else{trades.unshift(data);closeModal("tradeModal");renderApp("dashboard");toast("Trade saved","success")}}
async function saveProfile(){const row={first_name:$("#setFirst").value.trim(),surname:$("#setSurname").value.trim(),phone:$("#setPhone").value.trim(),workspace_name:$("#setWorkspace").value.trim()};const {error}=await sb.from("profiles").update(row).eq("id",currentUser.id);if(error)toast(error.message,"error");else{Object.assign(profile,row);$("#workspaceName").textContent=row.workspace_name;toast("Profile updated","success")}}
function exportData(){const blob=new Blob([JSON.stringify({profile,accounts,trades},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="tradevault-backup.json";a.click();URL.revokeObjectURL(a.href)}
function fmtMoney(v){const n=Number(v||0);return (n<0?"-$":"$")+Math.abs(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function logout(){if(sb)await sb.auth.signOut();showPublic()}
$("#loginBtn").onclick=()=>openAuth("login");$("#signupBtn").onclick=()=>openAuth("signup");$("#heroSignup").onclick=()=>openAuth("signup");$("#bottomSignup").onclick=()=>openAuth("signup");$("#pricingSignup").onclick=()=>openAuth("signup");$("#heroLogin").onclick=()=>openAuth("login");$("#userBtn").onclick=()=>{if(currentUser)showApp()};$("#logoutBtn").onclick=logout;$("#tradeForm").onsubmit=saveTrade;
$$("[data-close]").forEach(x=>x.onclick=()=>closeModal(x.dataset.close));$("#authModal").addEventListener("click",e=>{if(e.target.id==="authModal")closeModal("authModal")});$("#tradeModal").addEventListener("click",e=>{if(e.target.id==="tradeModal")closeModal("tradeModal")});
$$("[data-appview]").forEach(x=>x.onclick=()=>{renderApp(x.dataset.appview);$("#mobileAppMenu").closest(".app-topbar")});
$("#mobileAppMenu").onclick=()=>$(".app-sidebar").classList.toggle("open");
$("#mobileMenuBtn").onclick=()=>$("#mobileNav").classList.toggle("hidden");$("#mobileSignup").onclick=()=>openAuth("signup");
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("tv_theme",document.body.classList.contains("dark")?"dark":"light");$("#themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾";$("#appThemeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"}
if(localStorage.getItem("tv_theme")==="dark")document.body.classList.add("dark");$("#themeBtn").onclick=toggleTheme;$("#appThemeBtn").onclick=toggleTheme;
showPublic();
